# Generated by Django 4.2.22 on 2025-09-24 09:56

import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_when', '0008_courseversion_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdate',
            name='assignment_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contentdate',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contentdate',
            name='subsection_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userdate',
            name='first_component_block_id',
            field=opaque_keys.edx.django.models.UsageKeyField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdate',
            name='is_content_gated',
            field=models.BooleanField(default=False),
        ),
    ]
