# Generated by Django 4.2.21 on 2026-02-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_when', '0009_contentdate_assignment_title_contentdate_course_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userdate',
            index=models.Index(fields=['user', 'modified'], name='edx_when_us_user_id_980dee_idx'),
        ),
    ]
